package ar.edu.utn.frc.tup.lc.iv.services.impl;

import ar.edu.utn.frc.tup.lc.iv.clients.ChatGptRestTemplate;
import ar.edu.utn.frc.tup.lc.iv.dtos.openAPI.OpenAIResponseDTO;
import ar.edu.utn.frc.tup.lc.iv.services.ChatGptService;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.NoArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

/**
 * Implementation of the service to interact with the ChatGPT API.
 * This service is responsible for sending
 * requests to the API and processing the responses.
 */
@Service
@NoArgsConstructor
public class ChatGPTServiceImpl implements ChatGptService {


    /**
     * ObjectMapper instance for converting between Java objects and JSON.
     * This is used to deserialize the JSON response from the ChatGPT API into
     * an instance of OpenAIResponseDTO.
     */
    @Autowired
    private ObjectMapper objectMapper;

    /**
     * RestTemplate for making HTTP requests to the ChatGPT API.
     * This instance handles the communication with the API endpoint and
     * is responsible for sending requests and receiving responses.
     */
    @Autowired
    private ChatGptRestTemplate restTemplate;

    /**
     * The initial prompt used to set the system message for ChatGPT.
     * This prompt defines the behavior and context for the model, guiding it
     * on how to generate responses based on user input.
     */
    @Value(value = "${chatgpt.initial.prompt}")
    private String initialPrompt;

    /**
     * The initial prompt used to set the system message for ChatGPT.
     * This prompt defines the behavior and context for the model, guiding it
     * on how to generate responses based on user input.
     */
    @Value(value = "${chatgpt.initial.dashboard-prompt}")
    private String dashboardPrompt;

    /**
     * Obtains a response from ChatGPT based on the provided request.
     *
     * @param request The content of the user's message.
     * @return The response generated by ChatGPT in text format.
     * @throws IllegalArgumentException If an error occurs during
     * communication with the API or processing the response.
     */
    @Override
    public String getChatGPTResponse(String request) {
        try {
            String jsonBody = "{"
                    + "\"model\": \"gpt-3.5-turbo\","
                    + "\"messages\": ["
                    + "{\"role\": \"system\", \"content\": \"" + initialPrompt + "\"},"
                    + "{\"role\": \"user\", \"content\": \"" + request + "\"}"
                    + "]"
                    + "}";
            String response = restTemplate.getChatResponse(jsonBody).getBody();

            OpenAIResponseDTO openAIResponse = objectMapper.readValue(response, OpenAIResponseDTO.class);
            return openAIResponse.getChoices().get(0).getMessage().getContent();

        } catch (Exception e) {
            throw new IllegalArgumentException(e.getMessage(), e);
        }
    }

    /**
     * Obtains a response from ChatGPT based on the provided request.
     *
     * @param request The content of the user's message.
     * @return The response generated by ChatGPT in text format.
     * @throws IllegalArgumentException If an error occurs during
     * communication with the API or processing the response.
     */
    @Override
    public String getChatGPTResponseDashboard(String request) {
        try {
            String jsonBody = "{"
                    + "\"model\": \"gpt-3.5-turbo\","
                    + "\"messages\": ["
                    + "{\"role\": \"system\", \"content\": \"" + dashboardPrompt + "\"},"
                    + "{\"role\": \"user\", \"content\": \"" + request + "\"}"
                    + "]"
                    + "}";
            String response = restTemplate.getChatResponse(jsonBody).getBody();

            OpenAIResponseDTO openAIResponse = objectMapper.readValue(response, OpenAIResponseDTO.class);
            return openAIResponse.getChoices().get(0).getMessage().getContent();

        } catch (Exception e) {
            throw new IllegalArgumentException(e.getMessage(), e);
        }
    }

}
